
name: Notification par e-mail après push

on:
  push:
    branches:
      - main

jobs:
  notifier:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install nodemailer

      - name: Envoyer un e-mail
        uses: actions/github-script@v6
        with:
          script: |
            const nodemailer = require('nodemailer');

            const transporter = nodemailer.createTransport({
              service: 'gmail',
              auth: {
                user: '${{ secrets.GMAIL_USER }}',
                pass: '${{ secrets.GMAIL_PASSWORD }}',
              },
            });

            const mailOptions = {
              from: '${{  secrets.GMAIL_USER }}',
              to: '${{  secrets.RECIPIENT_EMAIL }}',
              subject: 'Nouveau fichier poussé',
              text: `Un nouveau fichier a été poussé vers le dépôt ${{ github.repository }} par ${{ github.actor }}.`,
            };

            transporter.sendMail(mailOptions, function (error, info) {
              if (error) {
                console.log(error);
              } else {
                console.log('E-mail envoyé: ' + info.response);
              }
            });
```

This ensures that `nodemailer` is installed before your script tries to use it.