name: Notification par e-mail après push

on:
  push:
    branches:
      - main  # Vous pouvez spécifier la branche souhaitée

jobs:
  notifier:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Envoyer un e-mail
        uses: actions/github-script@v6
        with:
          script: |
            const nodemailer = require('nodemailer');

            const transporter = nodemailer.createTransport({
              host: 'smtp.gmail.com',  // Ajout du serveur SMTP
              port: 587,  // Ajout du port SMTP
              secure: false, // true for 465, false for other ports
              auth: {
                user: '${{ secrets.GMAIL_USER }}',
                pass: '${{ secrets.GMAIL_PASSWORD }}',
              },
            });

            const mailOptions = {
              from: '${{ secrets.GMAIL_USER }}',
              to: '${{ secrets.RECIPIENT_EMAIL }}',
              subject: 'Nouveau fichier poussé',
              text: `Un nouveau fichier a été poussé vers le dépôt ${{ github.repository }} par ${{ github.actor }}.`,
            };

            transporter.sendMail(mailOptions, function (error, info) {
              if (error) {
                console.log(error);
              } else {
                console.log('E-mail envoyé: ' + info.response);
              }
            });
